inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/formtastic.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

Style/MultilineIfModifier:
  Enabled: false
