inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/new_defaults.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/performance.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/rails.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/formtastic.rb'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Metrics/BlockLength:
  Exclude:
    - 'config/environments/production.rb'
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails/DynamicFindBy:
  Whitelist:
    - 'find_by_path'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

Style/MultilineIfModifier:
  Enabled: false
