language: ruby
rvm: 2.2.2
addons:
  postgresql: "9.3"
before_install:
- gem update --system
- gem install bundler
- openssl aes-256-cbc -K $encrypted_b0ee5f2fe3a6_key -iv $encrypted_b0ee5f2fe3a6_iv -in .env.test.enc -out .env.test -d
before_script:
- psql -c 'create database drumknott_test;' -U postgres >/dev/null
- bundle exec rake db:migrate RAILS_ENV=test
script: bundle exec rake
sudo: false
