default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5 ) %>
  <% if ENV['DATABASE_URL'].nil? %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  <% end %>

development:
  <<: *default
  database: drumknott_development

test:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  database: drumknott_test
  <% end %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
