name: CI

on: [push]

env:
  RUBYOPT: "--enable-frozen-string-literal --debug-frozen-string-literal"

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Rubocop
      run: "bundle exec rubocop --format progress --format RubocopGithubAnnotationFormatter::AnnotationFormatter"

  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: drumknott
          POSTGRES_PASSWORD: drumknott
          POSTGRES_DB: drumknott_test
        ports:
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Sphinx
        run: "./bin/loadsphinx"

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        env:
          DATABASE_URL: postgres://drumknott:drumknott@127.0.0.1:${{ job.services.postgres.ports[5432] }}/drumknott_test
          INVOICE_FROM: Invoice CI
          REDIS_URL: "redis://127.0.0.1:${{ job.services.redis.ports[6379] }}/0"
          STRIPE_PLAN_ID: ${{ secrets.STRIPE_PLAN_ID }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: "bundle exec rspec --format RSpec::Github::Formatter"
